### ISSUE TITLE
Find functions that can be hoisted to top level (for things like Html.Lazy)

### ISSUE THREAD

**Issue by showell** [jfmengels/elm-review#1]
As we discussed on chat, it might be useful to warn folks about `let` function glitches for situations like using `Html.Lazy`.

Here's some code that may be fairly easy to adapt to elm-review data structures:

https://github.com/showell/elm-start/blob/truly-local-let-functions/src/CallGraph.elm

**Comment by showell** [comment]
I guess there are two pieces related to Html.Lazy

- Just finding that you wrap a `let` in lazy.
- Deciding what the advice is (either a) hoist it directly or b) explain how function is bound to args)

My code could help with the latter.

**Comment by jfmengels** [comment]
Hey @showell

I seem to have forgotten to follow up on our/this discussion.
I really want to see a review rule/package that helps with finding bad uses of `Html.lazy`.
With v2 that I released yesterday, I think the analysis can be pushed pretty far, much further than what you are describing (but definitely including it).

If no-one starts working on this and tells me, I'm pretty sure I will do so myself at one point.

I'll close this as I don't think this is relevant to the `elm-review` package (anymore?).
