### ISSUE TITLE
Docs for runOnModulesWithProjectData and runOnModules

### ISSUE THREAD

**Issue by sparksp** [jfmengels/elm-review#10]
The documentation for [Review.Test.runOnModulesWithProjectData] and [Review.Test.runOnModules] show an example of using the opposite function.

[Review.Test.runOnModulesWithProjectData]:https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Test#runOnModulesWithProjectData
[Review.Test.runOnModules]: https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Test#runOnModules

**Comment by jfmengels** [comment]
Thanks for reporting this @sparksp :blush:
