### ISSUE TITLE
`Review.ModuleNameLookupTable.moduleNameFor` support for `PrefixOperator`/`OperatorApplication`

### ISSUE THREAD

**Issue by SiriusStarr** [jfmengels/elm-review#105]
Currently, `Review.ModuleNameLookupTable.moduleNameFor` only supports `FunctionOrValue` in expressions, but it would be nice (if it wasn't terribly difficult to implement) if it worked for `PrefixOperator`s and `OperatorApplication`s as well, rather than having to hard code the various operators (since they aren't all in `Basics`).  (Also potentially more future-proof, if more operators are ever added to the language.)

**Comment by jfmengels** [comment]
I don't see any problem with this, and it should also not be too hard to implement either. Let's do it :+1: 

From what I can see, you'd only need to add similar code to [this](https://github.com/jfmengels/elm-review/blob/master/src/Review/Rule.elm#L5636-L5643) but for those nodes. Then the obvious test writing and documentation updating.

**Comment by SiriusStarr** [comment]
Closed by #106
