### ISSUE TITLE
Review.Test: display whitespace differences

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review#11]
The test failure message when the result of a fix is the same expect for some white-space is not very useful.

```text
    I found the following result after the fixes have been applied:
      `` `
        module A exposing (..)
        a = thing 
      `` `
    but I was expecting:
      `` `
        module A exposing (..)
        a = thing
      `` `
```

I think that we could do something like this:
- Check if the fix result is the same as expected, and pass the test if it is.
- If it isn't, replace all white-space (not newlines though) in both and re-compare.
- If they are not the same, then the difference is not (solely) related to white-space, and we should display the current error message
- If they are the same, then the difference is only white-space, and we can improve the error message.

I'm thinking we could improve the error message by splitting the texts in lines, and comparing each line. For the lines that are different, we could replace white-space by `·` (https://theasciicode.com.ar/extended-ascii-code/interpunct-space-dot-ascii-code-250.html), so we don't show the problem everywhere.

If someone wants to a better diff and highlight the differences in color (like Git diffs), that could be useful too (but the `·` will probably still be useful for color-blind people?).

## Pondering

- Maybe we should accept white-space differences, since we run `elm-format` afterwords anyway. I'm thinking this could influence indentation, so maybe we should report the ones at the beginning of lines, but for ones in the middle or at the end of lines we could give the user leeway without any impactful consequences?

## How to reproduce

Build a rule that reports anything and introduces white-space somewhere at the end of a line.

```elm
delcarationVisitor : Node a -> List (Error {})
delcarationVisitor node =
    Rule.errorWithFix
        { message = "Foo"
        , details = [ "Foo" ]
        }
        (Node.range node)
        [ Fix.insertAt (Node.range node).end " " ]
```

and have a rule that expects a fix without the additional

**Comment by sparksp** [comment]
Here's an example of `git diff` showing trailing whitespace. I think it is probably colour blind friendly (since it's solid blocks of colour).

![git-diff](https://user-images.githubusercontent.com/243893/83452006-d28c4080-a44f-11ea-9e3f-147cf5e0ad2f.png)
