### ISSUE TITLE
RFC: Remove direction from declarationVisitor

### ISSUE THREAD

**Issue by jfmengels** [jfmengels/elm-review#13]
Both declaration and expression visitors are visited twice
- on "enter", before the children have been visited
- on "exit", after the children have been visited

This is quite useful to know in which "context" you are: Am I inside a let..in expression, which function declaration am I, etc?

For `let..in` expression, this can be quite useful, as the direction-less alternative can be quite painful to write.

For declaration visitors though, the point of the "exit" visitor is, most often as I have seen, to remove the "current" function related information that were set in the "enter" visitor. But these will be overridden anyway by the next "enter" visit.

We might avoid a lot of visits by making the declaration visitor "direction-less", thus gaining in performance.

This will likely happen, unless scenarios are found where this simplifies the visit of a module drastically. If you know of any, please write them down as comments.

**Comment by sparksp** [comment]
[`NoUnused.Parameters`](https://github.com/jfmengels/review-unused/blob/master/src/NoUnused/Parameters.elm#L68-L69) uses `OnEnter` and `OnExit`.

<dl>
<dt>OnEnter</dt>
<dd>Record all the values from the arguments list in the context. The Expression visitor will then remove any values it comes across.</dd>

<dt>OnExit</dt>
<dd>Report any values remaining in the context.</dd>
</dl>

**Comment by jfmengels** [comment]
Yeah, a few of the rules I wrote also use it, but you could do it without.
Instead of doing something on declaration exit, you do it on declaration enter right before you do what you currently do on enter. That would work since the next thing that gets visited after a declaration exit is the next declaration's enter. For the last declaration, you would then do that in the final evaluation (which is not ideal, but doable)

I think having a withDeclarationExitVisitor and equivalent expression visitor makes sense. Considering how often the exit visitors are used (not that much), this would make the visitors simpler and the rules run a bit faster.

The only drawback is that the code for enter and exit, which are related, would be more separated in terms of lines of code than what they are today.

But I think this would be nice for the next major version 👍

**Comment by sparksp** [comment]
What I liked about using `OnExit` for `NoUnused.Parameters` was that I could get at the `Node` again and I didn't need to keep it in the context - this meant that `OnEnter` was only concerned with Strings (and context could be a `Set` instead of a `Dict` too).

Having the (same) code split between entering the next node and a final visitor sounds like a step backward to me, so I'm glad you like the idea of exit visitors.

**Comment by jfmengels** [comment]
That's a very good point :+1:

**Comment by jfmengels** [comment]
Implemented in v2.2.0 https://github.com/jfmengels/elm-review/releases/tag/2.2.0 :)
