### ISSUE TITLE
Incomplete sentence in docs

### ISSUE THREAD

**Issue by lydell** [jfmengels/elm-review#164]
https://github.com/jfmengels/elm-review/blob/2.13.1/src/Review/Rule.elm#L1029-L1030

```
Same as [`newModuleRuleSchema`](#newModuleRuleSchema), except that you can request for data to help initialize the context.
compared internally, which [may cause Elm to crash](https://package.elm-lang.org/packages/elm/core/latest/Basics#==).
```

There’s a sentence starting with “compared internally”. It looks like the start of the sentence has gone missing, or that a piece was left behind.

**Comment by lue-bird** [comment]
I think the missing part is
>**NOTE**: Do not store functions, JSON values or regular expressions in your contexts, as they will be

https://github.com/jfmengels/elm-review/blob/2.13.1/src/Review/Rule.elm#L963

**Comment by jfmengels** [comment]
Thanks for noticing!
The correct fix was actually to remove the "compared internally" sentence as that is only an issue for project contexts, not for module contexts.
