### ISSUE TITLE
binary operator parsing precendence bug

### ISSUE THREAD

**Issue by wolfadex** [jfmengels/elm-review#177]
**Describe the bug**
elm-review claims that `a + b /= 0` is invalid but the Elm compiler and elm-test don't have an issue with it. By wrapping the math in parens, like `(a + b) /= 0`, then it parses fine in elm-review.  This also applies to `a + b + c /= 0` where wrapping like `(a + b  +c ) /= 0` fixes it for elm-review.

**Additional context**
This was noticed after upgrading the dependency elm-syntax, so the bug might belong there more but I wanted to file it here since it does impact elm-review and I'm not 100% certain of the source/root cause.

edited:
Re-filed in elm-syntax as that's the source of the issue https://github.com/stil4m/elm-syntax/issues/258

**Comment by jfmengels** [comment]
Handling this in https://github.com/stil4m/elm-syntax/issues/258
