### ISSUE TITLE
Publish NoUnapprovedLicense

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/elm-review#22]
I use https://github.com/jfmengels/elm-review/blob/2b918beafe44102e6f4a46d0a43bad335b066a7b/tests/NoUnapprovedLicense.elm at work. I think it works well but it would be better if we didn't need to vendor it. Could this be published as a stand alone package?

**Comment by jfmengels** [comment]
Sounds good to me. Shall I make a new package `jfmengels/elm-review-license`?

**Comment by MartinSStewart** [comment]
Yes, that sounds like a good name for it.

**Comment by jfmengels** [comment]
Done https://package.elm-lang.org/packages/jfmengels/elm-review-license/latest/ :slightly_smiling_face:
