### ISSUE TITLE
Possible to use both elm-review and elm-test in existing project?

### ISSUE THREAD

**Issue by r-k-b** [jfmengels/elm-review#3]
I'm experimenting with writing a custom rule within an existing Elm project, and as part of that I'd like to have tests for the custom rule.

However, it's not clear how to arrange the `elm-review` files in a way that is compatible with `elm-test`?

For instance, running `elm-test init` creates the files in the `review` directory as expected, but when I `cd review` and run `elm-test`, I get various errors, depending on what combination of things I've tried.

If I put the test file under `review`, `elm-test` says it can't find anything under the `tests/` directory.

If I put the test file under `review/tests`, `elm-test` reports a "Confusing File" error.

If keep the test there and move `ReviewConfig.elm` into `review/src`, changing the elm.json to have `"source-directories": ["src"]`, then `elm-test` appears to work, while `elm-review` now complains about missing files.

I understand moving the rules and tests to their own package would solve this, but I'd prefer to keep it in the existing package if possible.

**Comment by jfmengels** [comment]
> I understand moving the rules and tests to their own package would solve this, but I'd prefer to keep it in the existing package if possible.

It would, but that's far from the wanted behavior. Thank you for asking instead of doing that :smile: 

The current folder structure does not work well with tests, and I'll change this in a future version of `elm-review init`. (I'll keep this issue open for others to find until that time).

The structure you wish to have is the following:

```
├── config
│   └── ReviewConfig.elm
├── elm.json
├── src
│   ├── Rule1.elm
│   ├── Rule2.elm
└── tests
    ├── Rule1Test.elm
    └── Rule2Test.elm
```

and the `elm.json` should have (at least) this as the source-directories

```elm
{
  "source-directories": [
     "config",
     "src"
  ]
}
```

**Comment by lydell** [comment]
Related: https://github.com/elm-explorations/test/issues/114

**Comment by jfmengels** [comment]
I'm closing this, as this should not be a problem in v2 anymore.
