### ISSUE TITLE
Ambiguous error location message is misleading

### ISSUE THREAD

**Issue by MartinSStewart** [jfmengels/elm-review#31]
**Describe the bug**
The SSCCE code below produces this error message 
```
AMBIGUOUS ERROR LOCATION

    Your test passes, but where the message appears is ambiguous.

    You are looking for the following error message:

      `Message`

    and expecting to see it under:

      ```
        a : Int
        a = 0
      ```

    I found 0 locations where that code appeared. Please use
    `Review.Test.atExactly` to make the part you were targetting unambiguous.

    Tip: I found them at:


```
At a glance it looks like it shouldn't be ambiguous where the error appears. What's probably causing problems is that on Windows, line breaks contain a \r which is getting inserted into the multiline string. I think this is confusing elm-review somehow.

Additionally, it's strange that at the end of the error message, there's `Tip: I found them at:` but nothing is listed.

**SSCCE (Short Self-Contained Correct Example)**
```elm
import Test exposing (..)
import Rule
import Review.Test

test = test "test" <|
                \_ ->
                    """module A exposing (..)

a : Int
a = 0"""
      |> Review.Test.run
          (Rule.newModuleRuleSchema "Rule" ()
              |> Rule.withDeclarationListVisitor
                  (\_ _ ->
                      ( [ Rule.error
                              { message = "Message"
                              , details = [ "" ]
                              }
                              { start = { column = 0, row = 3 }, end = { column = 5, row = 4 } }
                        ]
                      , ()
                      )
                  )
              |> Rule.fromModuleRuleSchema
          )
      |> Review.Test.expectErrors
          [ Review.Test.error
              { message = "Message"
              , details = [ "" ]
              , under = "a : Int\na = 0"
              }
              |> Review.Test.whenFixed ""
          ]
```

**Expected behavior**
Not sure but maybe elm-review could check if there's windows line endings present when it gets this error and warn that, that might be causing the issue.

**Additional context**
This happens on Windows only due to the way it uses \r\n as line breaks instead of just \n. So to reproduce this issue, you'll need to run it on Windows or replace 
```elm
"""module A exposing (..)

a : Int
a = 0"""
```
with 
```"module A exposing (..)\r\n\r\na:Int\r\na = 0"```

**Comment by jfmengels** [comment]
I just tried this SSCCE on master, and it seems to work as expected (well, we get an error about missing fixes).

I was able to reproduce the issue on 2.3.8 but not with 2.3.9.
I bisected the issue and the problem seems to have been fixed at some point through a bump of `elm-syntax`, so maybe the root cause of the issue was errors in the range given by `elm-syntax`.

Let me know if you can reproduce the issue still!

**Comment by MartinSStewart** [comment]
I don't have time now but I'll test this again with the latest version of elm-review at some point. I'll let you know if it works or not.

**Comment by jfmengels** [comment]
Can you try this again? 🙂

**Comment by MartinSStewart** [comment]
Sorry, I completely forgot about this. I don't have time to test it right now but I haven't seen it appear in a while. I think it's best if I just close the issue and I can reopen it if I run into in the future.
