### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by KasMA1990** [jfmengels/elm-review#4]
The link to the `Review.Rule` file in the "Write your own rule" section is dead.

**Comment by jfmengels** [comment]
Hey @KasMA1990 :wave: 

That's unfortunately a problem with the difference in handling links in the packages website and in GitHub. The link works fine from the packages website (see [here](https://package.elm-lang.org/packages/jfmengels/elm-review/1.0.0/#write-your-own-rule)), but not from GitHub.

I want to prioritize having the links in the packages website work. It would be nice to have both work somehow, but I don't know of a way :/

Thanks for reporting though :wink:
