### ISSUE TITLE
Saying "no" in `elm-review init` causes a hang

### ISSUE THREAD

**Issue by KasMA1990** [jfmengels/elm-review#6]
I ran the init command from Git bash on Windows 10, and when prompted if I wanted to create elm.json and ReviewConfig.elm files, I typed "n" and hit Enter. Then the client froze.

**Comment by KasMA1990** [comment]
The same thing happens if I say yes, although the review folder and files are created correctly. The command just never seems to exit

**Comment by jfmengels** [comment]
This is more of an error for the [CLI](https://github.com/jfmengels/node-elm-review/issues/).

I just released a new version of it. Can you try it and open an issue there if it still doesn't work?
