### ISSUE TITLE
Tried get started, got strange error

### ISSUE THREAD

**Issue by mattiasw2** [jfmengels/elm-review#9]
c:\data6\cs\sss6\sss6elm>
c:\data6\cs\sss6\sss6elm>npx elm-review init
npx: installed 1 in 1.619s
Path must be a string. Received undefined
C:\Users\matti\AppData\Roaming\npm-cache\_npx\26080\node_modules\elm-review\bin\elm-review
Unexpected token {

**Comment by mattiasw2** [comment]
As you see it is Windows, maybe that is the reason? What do you use?

**Comment by jfmengels** [comment]
Hello @mattiasw2 :wave: 

I am using Linux Ubuntu, and have not been able to test it extensively on Windows, but I know that other Windows have been able to make it work.

I can't find out the problem you have with the information you have given me unfortunately :/

I suggest:
- Installing `elm-review` in your project (`npm i -D elm-review`) or globally (`npm i -g elm-review`). It looks like `npx` just installed it for you, and it might do something funny.
- Running with `--debug` (`npx elm-review --debug`). You will likely get a lot more (unuseful) text, but the error will be displayed with the stacktrace, which should give a clue as to where the error occurs.

Thanks for reporting the error and trying it out! :)

**Comment by jfmengels** [comment]
I'm closing this as I don't have an actionable item, but let me know (in the `jfmengels/node-elm-review` project) if the problem keeps happening.
