### ISSUE TITLE
elm-review cannot parse {}

### ISSUE THREAD

**Issue by xarvh** [jfmengels/elm-review#99]
**Describe the bug**

If the Elm code contains an empty record, elm-review fails to parse the file and blames the user.

**SSCCE (Short Self-Contained Correct Example)**

`x = {}`

1. Add the SSCCE code to any elm module
2. Run elm-review on the module

**Expected behavior**
elm-review should correctly parse valid Elm code, or at least not blame the user.

**Comment by jfmengels** [comment]
Hi @xarvh 👋 

This is a problem with https://github.com/stil4m/elm-syntax, the parser that `elm-review` uses.

I could reproduce the issue with `x = \{} -> 1` from your initial issue, but not with `x = {}` though. Could you re-verify this, or provide another SSCCE? 🤔 

Also, please make sure you have the latest version of `elm-syntax` in your `review/elm.json`, just in case.

**Comment by jfmengels** [comment]
A new version of `stil4m/elm-syntax` (7.2.5) has been released which fixes the issue of parsing empty records in patterns (`\{} -> 1`).

You should go to your review configuration, and update the version for that library in `review/elm.json`.

Let me know if that fixes the issue you were encountering. I'll close the issue in the meantime, but we'll re-open if that didn't solve the issue.

**Comment by xarvh** [comment]
Upgrading `stil4m/elm-syntax` to 7.2.5 indeed fixes the issue.
Thank you.
